DEX_LABEL = "Dex"
PKM_LABEL = "Pokemon"
USER_ID_LABEL = "Discord ID"
IMAGE_LABEL = "Image"
COMMENT_LABEL = "Comment"
APPROVED_LABEL = "Approved"
SEPARATOR_LABEL = ""
THEME_LABEL = "Theme"
RULES_LABEL = "Rules"
DEADLINE_LABEL = "Deadline"
CLAIM_MAX_LABEL = "Claim Max"
UNAPP_MAX_LABEL = "Unapproved Max"

ENGLISH_NAME_LABEL_P = "name.en"
DEX_LABEL_P = "id"

SUBMIT_BTN_LABEL = "Submit"
COMMENT_BTN_LABEL = "Add comment"
