DEX_LABEL = "Dex"
PKM_LABEL = "Pokemon"
USERNAME_LABEL = "Discord Username"
USER_ID_LABEL = "Discord ID"
IMGUR_LABEL = "Imgur"
CMT_LABEL = "Comment"
APPROVED_LABEL = "Approved"

ENGLISH_NAME_LABEL_P = "name.en"
DEX_LABEL_P = "id"

TOPIC_LABEL = "Topic"
RULES_LABEL = "Rules"
DEADLINE_LABEL = "Deadline"
CLAIM_MAX_LABEL = "Claim Max"
UNAPP_MAX_LABEL = "Unapproved Max"
